import { DataContextProvider } from "./context/DataContext";
import { AuthProvider } from "./context/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
//Font awesome
import { library } from "@fortawesome/fontawesome-svg-core";
import { faTwitter } from "@fortawesome/free-brands-svg-icons";
import { faTrashCan } from "@fortawesome/free-solid-svg-icons";
import { faFilePen } from "@fortawesome/free-solid-svg-icons";
import { SalonProvider } from "./context/SalonProvider";

library.add(faTwitter, faTrashCan, faFilePen);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SalonProvider>
          <AuthProvider>
            <DataContextProvider>{children}</DataContextProvider>
          </AuthProvider>
        </SalonProvider>
      </body>
    </html>
  );
}
