// "use client"
import DataContext, { DataContextProvider } from "./context/DataContext";
import "./globals.css";
import { Inter } from "next/font/google";
//Font awesome
import { library } from "@fortawesome/fontawesome-svg-core";
import { faTwitter } from "@fortawesome/free-brands-svg-icons";
import {
  faTrashCan,
  faFilePen,
  faSquarePlus,
} from "@fortawesome/free-solid-svg-icons";
// import { faFilePen } from "@fortawesome/free-solid-svg-icons";
import { SalonProvider } from "./context/SalonProvider";
import NavPrincipal from "./components/NavPrincipal";
import firebaseApp from "@/firebase";
import { applyActionCode, getAuth } from "firebase/auth";
import { AuthProvider } from "./context/AuthProvider";
import { DeliveryProvider } from "./context/DeliveryContext";


library.add(faTwitter, faTrashCan, faFilePen);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mercadito",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <DeliveryProvider>
            <SalonProvider>
              <DataContextProvider>
                <NavPrincipal />
                {children}
              </DataContextProvider>
            </SalonProvider>
          </DeliveryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
